name: CI

on: [push, pull_request]

jobs:
  tests-on-x86-mac:
    runs-on: macos-13
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['3.2']
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests with Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle exec rake
  tests-on-x86-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby-version }} on ubuntu
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests on docker(x86)
        run: bundle exec rake


